# Generated by Django 4.1.7 on 2023-04-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('address', models.TextField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
